### ISSUE TITLE
[lang-test] Разработать описание ЯП в файле для автоматизации

### ISSUE THREAD

**Issue by RaSla** [RaSla/lang-test#4]
Надо разработать описательный формат для применения в YAML файлах, используя которые, будущая программа сможет проводить пакетное тестирование разных ЯП.

Каждый ЯП должен описываться примерно таким набором:
```yaml
lang:
  name: php
  type: 'interpreter'  # or 'compile'
test:
  native:
    # compile_cmd:
    run_cmd: php test_php.php
  docker:
    - version: 7.0
      image: php:7.0
...
```

Необходимо:
* разработать формат такого файла описания ЯП
* описать его в MD-файле

особенно нюансы
* где должны лежать файлы? - иерархия каталогов и файлов
* как проводить тест с разными версиями ЯП (в докере) ?
